# -*- coding: utf-8 -*-
"""WikiPathways RDF in Google Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/126diGs9webJcbl6qgPGLtOKyOO_40YmH
"""

from rdflib import Graph
from urllib.request import urlretrieve
import zipfile
import os

g = Graph()
g.parse("https://data.wikipathways.org/current/rdf/wikipathways-rdf-void.ttl")

downloadURL_query = """
PREFIX dcat:     <http://www.w3.org/ns/dcat#>

SELECT DISTINCT ?url
WHERE {
  [] dcat:downloadURL ?url .
}
"""

qres = g.query(downloadURL_query)
for row in qres:
    url = row.url
    prefix, delim, filename = url.rpartition('/')
    print(f"{url} -> {filename}")
    urlretrieve(url, filename)
    with zipfile.ZipFile(filename, mode="r") as archive:
        for file in archive.namelist():
            if file.endswith(".ttl"):
                print(f"reading {file}")
                ttl_file = zipfile.Path(filename, file)
                g.parse(data=ttl_file.read_text())
        os.remove(filename)

metadata_query = """
SELECT DISTINCT ?dataset (str(?titleLit) as ?title) ?date ?license
WHERE {
   ?dataset a void:Dataset ;
   dcterms:title ?titleLit ;
   dcterms:license ?license ;
   pav:createdOn ?date .
}
"""
qres = g.query(metadata_query)
for row in qres:
    print(f"dataset: {row.dataset}")
    print(f"title: {row.title}")
    print(f"date: {row.date}")
    print(f"license: {row.license}")

nt_file = "wikipathways_all.nt"
g.serialize(destination=nt_file, format="nt")